name: Documentation Build and Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-deploy:
    name: Build and Deploy Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv âš¡
        uses: astral-sh/setup-uv@v3

      - name: Create and Activate Virtual Environment ğŸ
        # This step creates a standard .venv directory using Python 3.12
        run: |
          uv venv --python 3.13
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Install dependencies ğŸ“¦
        run: |
          uv pip install sphinx
          uv pip install -e .

      - name: Build Sphinx Documentation ğŸ—ï¸
        run: |
          cd docs
          sphinx-apidoc -o source ../src/bayinx -f
          make html

      - name: Deploy to GitHub Pages ğŸŒ
        uses: peaceiris/actions-gh-pages@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          publish_branch: gh-pages
